{% set name = "testflows.asserts" %}
{% set version = "7.0.231001.1010150" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/testflows.asserts-{{ version }}.tar.gz
  sha256: adf2e9f0c0d12a5298788f6714a67d9caa1d223350fe093f2e2f673bac25a0a9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - testflows.asserts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/testflows/testflows-asserts
  summary: TestFlows - Asserts Assertion Library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
